version: '3.9'

###########################
#     S E R V I C E S     #
###########################
services:
    #############
    #  PHP-FPM  #
    #############
    php-fpm:
        restart: always
        build:
            context: ./docker/php-fpm/prod
            args:
                - USER_UID
                - USER_GID
        volumes:
            - ./app/:/var/www/
            - ./docker/php-fpm/prod/zz-performance.ini:/usr/local/etc/php/conf.d/zz-performance.ini

    ###########
    #  NGINX  #
    ###########
    nginx:
        restart: always
        build:
            context: ./docker/nginx
            args:
                - USER_UID
                - USER_GID
        volumes:
            - ./app/:/var/www/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php-fpm
        ports:
            - "127.0.0.1:8110:80"
