version: '3.9'

###########################
#     S E R V I C E S     #
###########################
services:
    #############
    #   MYSQL   #
    #############
    mysql:
        restart: always
        build:
            context: ./docker/mysql
            args:
                - USER_UID
                - USER_GID
        environment:
            MYSQL_DATABASE: 'questions'
            MYSQL_USER: 'questions'
            MYSQL_PASSWORD: 'questions_password'
            MYSQL_ROOT_PASSWORD: 'root_password'
        volumes:
            - ./docker/mysql/data/:/var/lib/mysql/

    #############
    #  PHP-FPM  #
    #############
    php-fpm:
        restart: always
        build:
            context: ./docker/php-fpm/dev
            args:
                - USER_UID
                - USER_GID
        depends_on:
            - mysql
            - redis
            - rabbitmq
        volumes:
            - ./app/:/var/www/
            - ./docker/php-fpm/zz-perfomance.ini:/usr/local/etc/php/conf.d/zz-perfomance.ini

    ###########
    #  NGINX  #
    ###########
    nginx:
        restart: always
        build:
            context: ./docker/nginx
            args:
                - USER_UID
                - USER_GID
        volumes:
            - ./app/:/var/www/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php-fpm
        ports:
            - "127.0.0.1:8110:8110"
            - "127.0.0.1:8120:8120"

    ###########
    #  REDIS  #
    ###########
    redis:
        restart: always
        build:
            context: ./docker/redis
            args:
                - USER_UID
                - USER_GID
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - ./docker/redis/redis.conf:/etc/redis.conf
        sysctls:
            net.core.somaxconn: '512'

    ################
    #   RABBITMQ   #
    ################
    rabbitmq:
        restart: always
        build:
            context: ./docker/rabbitmq
            args:
                - USER_UID
                - USER_GID
        ports:
            - "127.0.0.1:5672:5672"
            - "127.0.0.1:15672:15672"
        environment:
            RABBITMQ_USERNAME: 'rabbitmq_user'
            RABBITMQ_PASSWORD: 'rabbitmq_password'
        volumes:
            - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
