frontend:
    resource: ../../src/Core/Controller/Frontend/
    type: annotation
    name_prefix: 'frontend_'
    host: '%app.frontend.domain%'

backend:
    resource: ../../src/Core/Controller/Backend/
    type: annotation
    name_prefix: 'backend_'
    host: '%app.backend.domain%'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
