framework:
    assets:
        packages:
            frontend:
                json_manifest_path: '%kernel.project_dir%/public/assets-frontend/manifest.json'
            backend:
                json_manifest_path: '%kernel.project_dir%/public/assets-backend/manifest.json'
