framework:
    cache:
        # Для приложения используется кеш в Redis (С инвалидацией по тегам)
        default_redis_provider: '%env(REDIS_DSN)%'
        app: cache.adapter.redis_tag_aware

        # Для системного кеша используются файлы
        system: cache.adapter.system

        # Pools
        pools:
            # Для нужд приложения
            my_cache_pool:
                adapter: cache.app
                default_lifetime: 3600
            # Для нужд Rate Limiter
            rate_limiter:
                adapter: cache.app
