doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
        mappings:
            App\Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'App\Core\Entity'
                alias: App\Core
            App\Users:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Users/Entity'
                prefix: 'App\Users\Entity'
                alias: App\Users
            App\Questions:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Questions/Entity'
                prefix: 'App\Questions\Entity'
                alias: App\Questions
