framework:
  rate_limiter:
    # Регистрация на сайте
    user_registration:
      policy: 'fixed_window'
      limit: 60
      interval: '60 minutes'
    # Восстановление пароля
    user_password_restore:
        policy: 'fixed_window'
        limit: 60
        interval: '60 minutes'
