twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/backend': backend
        '%kernel.project_dir%/templates/frontend': frontend
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        mediaUrl: '%env(APP_MEDIA_URL)%'

when@test:
    twig:
        strict_variables: true
