name: Static analysis

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

defaults:
    run:
        shell: bash

jobs:
    # Psalm
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: none

            - name: Checkout target branch
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                  composer install --working-dir=app/ --no-interaction --no-plugins --no-progress --no-scripts --ansi

            - name: Run Psalm
              run: |
                  php ./app/vendor/bin/psalm  --no-cache --show-info=true --config=./app/psalm.xml --no-progress || php ./app/vendor/bin/psalm  --no-cache --show-info=true --config=./app/psalm.xml --output-format=github --no-progress
