name: Symfony 6 Questions

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            # Checkout repo
            -   uses: actions/checkout@v2

            # Copy env.test.local config
            -   name: Copy .env.test.local
                run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

            # Get Composer cache
            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            # Composer install
            -   name: Composer install
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
